const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const net = require('node:net');
const { spawn } = require('node:child_process');
const { chromium } = require('@playwright/test');
const delay = ms => new Promise(r => setTimeout(r, ms));
test('migrated spaces, collaborative tabs and shared definitions', { timeout: 120000 }, async () => {
  const root = path.resolve(__dirname, '../..');
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'space-tabs-test-'));
  const sock = net.createServer(); await new Promise(r => sock.listen(0, '127.0.0.1', r)); const port = sock.address().port; await new Promise(r => sock.close(r));
  let server = spawn(path.join(root, 'backend/.venv/bin/python'), [path.join(root, 'backend/tests/tabs_fixture_server.py'), tmp, String(port)], { cwd: root });
  let log = ''; server.stdout.on('data', b => log += b); server.stderr.on('data', b => log += b);
  let browser;
  try {
    const base = `http://127.0.0.1:${port}`;
    for (let i = 0; i < 80; i++) { try { if ((await fetch(base)).ok) break; } catch {} await delay(100); }
    browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const login = await context.request.post(base + '/api/login', { data: { username: 'admin', password: 'admin' } }); assert.equal(login.status(), 200);
    const spaces = await (await context.request.get(base + '/api/spaces')).json(); assert.ok(spaces.spaces.some(s => s.id === 'demo'));
    const listing = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(listing.tabs.length, 2);
    const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    // Restore through the existing space reference to exercise compatibility.
    await page.evaluate(() => { localStorage.setItem('taskScriptLastSpace', 'demo'); });
    await page.getByRole('button', { name: 'Switch space' }).click();
    const row = page.locator('.space-item').filter({ has: page.locator('.space-label', { hasText: /^demo$/ }) });
    await row.getByRole('button', { name: 'Connect', exact: true }).click();
    await page.locator('.space-tabs').waitFor({ state: 'visible' });
    await page.getByRole('tab', { name: 'main', exact: true }).waitFor();
    assert.equal(await page.locator('.space-tab-menu').count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Open', exact: true }).textContent(), '');
    assert.equal(await page.getByRole('button', { name: 'Add', exact: true }).textContent(), '');
    await page.getByRole('button', { name: 'Open', exact: true }).click();
    await page.getByRole('menu', { name: 'Closed tabs' }).waitFor();
    assert.equal(await page.locator('.tab-dialog').count(), 0);
    assert.equal(await page.getByRole('menu').textContent(), 'No closed tabs.');
    await page.getByRole('button', { name: 'Open', exact: true }).click();
    assert.equal(await page.getByRole('menu').count(), 0);
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    assert.equal(await page.getByRole('menu').count(), 0);
    await page.getByRole('tab', { name: 'main', exact: true }).click({ button: 'right' });
    await page.getByRole('menu', { name: 'Options for main' }).waitFor();
    assert.equal(await page.getByRole('menuitem', { name: 'Appearance', exact: true }).locator('i').count(), 1);
    assert.equal(await page.getByRole('menuitem', { name: 'Icon', exact: true }).count(), 0);
    assert.equal(await page.getByRole('menuitem', { name: 'Color', exact: true }).count(), 0);
    await page.locator('#task-editor').evaluate(el => el.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true })));
    assert.equal(await page.getByRole('menu').count(), 0);
    await page.getByRole('tab', { name: 'main', exact: true }).press('Shift+F10');
    await page.getByRole('menu').waitFor();
    await page.keyboard.press('ArrowDown');
    assert.equal(await page.getByRole('menuitem', { name: 'Rename', exact: true }).evaluate(el => el === document.activeElement), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('menu').count(), 0);
    assert.equal(await page.locator('#task-editor').inputValue(), 'Demo:\n% Task\n#urgent @anna !todo\n1.10.2026-5.10.2026\n');
    await page.getByRole('button', { name: 'Add', exact: true }).click();
    await page.screenshot({ path: '/tmp/add-tab-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/add-tab-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.getByRole('textbox', { name: 'Tab name' }).fill('release');
    await page.getByRole('button', { name: 'Create', exact: true }).click();
    await page.getByRole('tab', { name: 'release', exact: true }).waitFor();
    await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: /release$/, exact: false }) }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Appearance', exact: true }).click();
    assert.equal(await page.getByRole('searchbox').count(), 0);
    assert.equal(await page.locator('.tab-icon-choice').count(), 64);
    assert.equal(await page.locator('.tab-icon-choice').first().getAttribute('aria-label'), 'No icon');
    assert.equal(await page.locator('.tab-icon-choice').first().textContent(), '');
    await page.screenshot({ path: '/tmp/tab-icon-picker-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/tab-icon-picker-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.getByRole('button', { name: 'Unicorn', exact: true }).click();
    await page.getByRole('tab', { name: '🦄 release', exact: true }).waitFor();
    assert.equal(await page.getByRole('dialog', { name: 'Tab appearance' }).isVisible(), true);
    assert.equal(await page.locator('.tab-color-preview-tab').textContent(), '🦄 release');
    assert.equal(await page.locator('.tab-color-choices button').first().getAttribute('aria-label'), 'Default');
    await page.getByRole('textbox', { name: 'Hex color', exact: true }).fill('#8b5cf6');
    assert.equal(await page.getByLabel('Custom tab color', { exact: true }).inputValue(), '#8b5cf6');
    await page.screenshot({ path: '/tmp/tab-color-picker-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/tab-color-picker-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.locator('.tab-dialog').waitFor({ state: 'hidden' });
    const customColor = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(customColor.tabs.find(t => t.name === 'release').appearance.color, '#8b5cf6');
    const coloredTab = page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: '🦄 release', exact: true }) });
    for (const theme of ['light', 'dark']) {
      await page.evaluate(theme => { document.documentElement.dataset.theme = theme; }, theme);
      assert.equal(await coloredTab.locator('.space-tab-select').evaluate(el => getComputedStyle(el, '::after').backgroundColor), 'rgb(139, 92, 246)');
      assert.equal(await coloredTab.evaluate(el => {
        el.classList.add('task-tab-hover');
        const color = getComputedStyle(el, '::before').backgroundColor;
        el.classList.remove('task-tab-hover');
        return color;
      }), 'rgb(139, 92, 246)');
    }
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.getByRole('tab', { name: '🦄 release', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Appearance', exact: true }).click();
    await page.getByRole('button', { name: 'Default', exact: true }).click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.locator('.tab-dialog').waitFor({ state: 'hidden' });
    const resetColor = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(resetColor.tabs.find(t => t.name === 'release').appearance.color, undefined);
    await page.getByRole('tab', { name: '🦄 release', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Appearance', exact: true }).click();
    await page.getByRole('button', { name: '#5d6bff', exact: true }).click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.locator('.tab-dialog').waitFor({ state: 'hidden' });
    const refreshed = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const release = refreshed.tabs.find(t => t.name === 'release');
    assert.equal(release.appearance.icon, '🦄'); assert.equal(release.appearance.color, '#5d6bff');
    const defs = refreshed.tabs.find(t => t.kind === 'defs');
    const defsText = await (await context.request.get(base + `/api/spaces/${defs.id}/`)).text();
    assert.match(defsText, /tabs:\n        release:\n            icon: 🦄/);
    await page.getByRole('tab', { name: '🦄 release', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Appearance', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Unicorn', exact: true }).getAttribute('aria-pressed'), 'true');
    await page.getByRole('button', { name: 'No icon', exact: true }).click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByRole('tab', { name: 'release', exact: true }).waitFor();
    await page.getByRole('tab', { name: 'release', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Appearance', exact: true }).click();
    await page.getByRole('button', { name: 'Fox', exact: true }).click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByRole('tab', { name: '🦊 release', exact: true }).waitFor();
    await page.getByRole('tab', { name: '🦊 release', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Appearance', exact: true }).click();
    await page.getByRole('button', { name: 'Unicorn', exact: true }).click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByRole('tab', { name: '🦄 release', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Close release', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('[role=tab]')].some(t => t.textContent.includes('release')));
    const closed = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.ok(closed.tabs.find(t => t.id === release.id).filename.startsWith('.'));
    await page.getByRole('button', { name: 'Open', exact: true }).click();
    const openBounds = await page.getByRole('button', { name: 'Open', exact: true }).boundingBox();
    const dropdownBounds = await page.getByRole('menu', { name: 'Closed tabs' }).boundingBox();
    assert.ok(dropdownBounds.y >= openBounds.y + openBounds.height);
    assert.equal(await page.locator('.tab-dialog').count(), 0);
    await page.screenshot({ path: '/tmp/open-tab-dropdown.png' });
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('menu').count(), 0);
    await page.getByRole('button', { name: 'Open', exact: true }).press('ArrowDown');
    await page.getByRole('menuitem', { name: '🦄 release', exact: true }).click();
    await page.getByRole('tab', { name: '🦄 release', exact: true }).waitFor();
    assert.equal(await page.getByRole('menu').count(), 0);
    await page.locator('#code-editor .cm-content').click();
    await page.keyboard.insertText('% Release task\n#urgent @anna !todo');
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('Release task'));
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.startsWith('Demo:'));
    await page.getByRole('tab', { name: '🦄 release', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.startsWith('% Release task'));
    await page.locator('#undo-button').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value === '');
    await page.locator('#redo-button').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.startsWith('% Release task'));
    const contents = await (await context.request.get(base + `/api/tab-spaces/${listing.id}/contents`)).json();
    const currentDefs = contents.documents.find(d => d.kind === 'defs');
    const update = await context.request.post(base + `/api/tab-spaces/${listing.id}/definitions`, { data: { changes: [{ id: currentDefs.id, expected: currentDefs.text, text: currentDefs.text.replace('#551188', '#118855') }] } });
    assert.equal(update.status(), 200);
    await page.waitForFunction(() => [...document.querySelectorAll('.task-node')].some(el => getComputedStyle(el).backgroundColor === 'rgb(17, 136, 85)'));
    const second = await context.newPage(); await second.goto(base);
    await second.getByRole('tab', { name: '🦄 release', exact: true }).waitFor();
    await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: /release$/, exact: false }) }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Copy', exact: true }).click();
    await page.getByRole('textbox', { name: 'Copy name', exact: true }).waitFor();
    await page.screenshot({ path: '/tmp/copy-tab-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/copy-tab-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.getByRole('button', { name: 'Copy', exact: true }).click();
    await page.locator('.tab-dialog').waitFor({ state: 'hidden' });
    await second.getByRole('tab', { name: '🦄 release_copy', exact: true }).waitFor();
    await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: /release_copy$/, exact: false }) }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Rename', exact: true }).click();
    await page.getByRole('textbox', { name: 'New tab name' }).fill('next');
    await page.screenshot({ path: '/tmp/rename-tab-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/rename-tab-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.getByRole('button', { name: 'Rename', exact: true }).click();
    await page.locator('.tab-dialog').waitFor({ state: 'hidden' });
    await page.getByRole('tab', { name: '🦄 next', exact: true }).waitFor();
    await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: /next$/, exact: false }) }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Move left', exact: true }).click();
    await page.waitForFunction(() => [...document.querySelectorAll('.space-tab-select')].map(e => e.textContent.trim()).join('|') === 'defs|main|🦄 next|🦄 release');
    await page.waitForFunction(() => [...document.querySelectorAll('.space-tab')].every(el => el.getAnimations().length === 0));
    const draggedTab = page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: '🦄 next', exact: true }) });
    const mainTab = page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: 'main', exact: true }) });
    const sourceBounds = await draggedTab.boundingBox();
    const mainBounds = await mainTab.boundingBox();
    const releaseBounds = await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: '🦄 release', exact: true }) }).boundingBox();
    await page.mouse.move(sourceBounds.x + sourceBounds.width / 2, sourceBounds.y + sourceBounds.height / 2);
    await page.mouse.down();
    await page.mouse.move(mainBounds.x + mainBounds.width / 4, mainBounds.y + mainBounds.height / 2, { steps: 10 });
    await page.mouse.move(mainBounds.x + mainBounds.width / 4 + 1, mainBounds.y + mainBounds.height / 2);
    await page.locator('.space-tab-drop-gap').waitFor({ state: 'visible' });
    assert.equal(await page.locator('.space-tab.drop-target').count(), 0);
    await page.waitForFunction(() => [...document.querySelectorAll('.space-tab')].some(el => new DOMMatrix(getComputedStyle(el).transform).m41 >= 17));
    await page.screenshot({ path: '/tmp/tab-reorder-gap.png' });
    await page.mouse.move(releaseBounds.x + releaseBounds.width * .85, releaseBounds.y + releaseBounds.height / 2, { steps: 10 });
    await page.mouse.move(releaseBounds.x + releaseBounds.width * .85 + 1, releaseBounds.y + releaseBounds.height / 2);
    await page.locator('.space-tab-drop-gap').waitFor({ state: 'visible' });
    const gapBounds = await page.locator('.space-tab-drop-gap').boundingBox();
    await page.mouse.move(gapBounds.x + gapBounds.width / 2, gapBounds.y + gapBounds.height / 2);
    await page.evaluate(() => {
      window.tabReorderAnimations = 0;
      const animate = Element.prototype.animate;
      Element.prototype.animate = function (...args) {
        if (this.classList.contains('space-tab')) window.tabReorderAnimations++;
        return animate.apply(this, args);
      };
    });
    await page.mouse.up();
    await page.waitForFunction(() => [...document.querySelectorAll('.space-tab-select')].map(e => e.textContent.trim()).join('|') === 'defs|main|🦄 release|🦄 next');
    assert.equal(await page.locator('.space-tab.drop-target').count(), 0);
    assert.equal(await page.locator('.space-tab-drop-gap').isVisible(), false);
    assert.ok(await page.evaluate(() => window.tabReorderAnimations > 0), 'dropping between tabs animates their new positions');
    await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: /defs$/, exact: false }) }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Close', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('.space-tab-select')].some(e => e.textContent.trim() === 'defs'));
    await page.waitForFunction(() => [...document.querySelectorAll('.task-node')].some(el => getComputedStyle(el).backgroundColor === 'rgb(17, 136, 85)'));
    const beforeDisk = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const diskTab = beforeDisk.tabs.find(t => t.name === 'release');
    const diskDir = path.join(tmp, 'spaces', beforeDisk.path);
    await fs.rename(path.join(diskDir, diskTab.filename), path.join(diskDir, '12_external.txt'));
    await second.getByRole('tab', { name: '🦄 external', exact: true }).waitFor();
    const afterDisk = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(afterDisk.tabs.find(t => t.name === 'external').id, release.id);
    // Definitions are editable without rendering shared tasks into task views.
    await page.getByRole('button', { name: 'Open', exact: true }).click();
    await page.getByRole('menuitem', { name: 'defs', exact: true }).click();
    await page.waitForFunction(() => document.documentElement.dataset.tabMode === 'defs');
    assert.equal(await page.locator('.graph-panel').isVisible(), false);
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('background: #118855'));
    assert.match(await page.locator('#task-editor').inputValue(), /background: #118855/);
    await page.getByRole('tab', { name: '🦄 next', exact: true }).click();
    await page.locator('.space-tab').filter({ has: page.getByRole('tab', { name: /next$/, exact: false }) }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Delete', exact: true }).click();
    const confirmation = page.locator('.tab-dialog');
    assert.equal(await confirmation.locator('.modal-actions').getByRole('button').count(), 2);
    assert.equal(await confirmation.getByRole('button', { name: 'Delete', exact: true }).getAttribute('class'), 'toolbar-button danger');
    await page.screenshot({ path: '/tmp/tab-delete-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/tab-delete-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await confirmation.getByRole('button', { name: 'Delete', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('[role=tab]')].some(t => t.textContent.includes('next')));
    await page.getByRole('tab', { name: '🦄 external', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('Release task'));
    // Restart with real collaborative stores, then restore the same stable tab.
    await second.close();
    server.kill('SIGTERM');
    await new Promise(r => { if (server.exitCode !== null) r(); else server.on('exit', r); });
    server = spawn(path.join(root, 'backend/.venv/bin/python'), [path.join(root, 'backend/tests/tabs_fixture_server.py'), tmp, String(port)], { cwd: root });
    server.stdout.on('data', b => log += b); server.stderr.on('data', b => log += b);
    for (let i = 0; i < 80; i++) { try { if ((await fetch(base)).ok) break; } catch {} await delay(100); }
    await page.reload();
    await page.getByRole('tab', { name: '🦄 external', exact: true }).waitFor();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('Release task'));
    const restarted = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(restarted.tabs.find(t => t.name === 'external').id, release.id);
    assert.ok(!restarted.tabs.some(t => t.name === 'next'));
    await page.locator('.app-boot-loader').waitFor({ state: 'hidden' });
    await page.screenshot({ path: '/tmp/space-tabs-browser.png' });
    await page.getByRole('tab', { name: '🦄 external', exact: true }).click({ button: 'right' });
    await page.getByRole('menu').waitFor();
    await page.screenshot({ path: '/tmp/space-tabs-context-light.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await page.screenshot({ path: '/tmp/space-tabs-context-dark.png' });
    await page.keyboard.press('Escape');
    // Closing every tab reveals the complete list directly in the workspace.
    for (const name of ['defs', 'main', 'external']) {
      await page.getByRole('button', { name: `Close ${name}`, exact: true }).click();
      await page.waitForFunction(name => ![...document.querySelectorAll('.space-tab-select')].some(el => el.textContent.trim().endsWith(name)), name);
    }
    await page.waitForFunction(() => document.documentElement.dataset.tabMode === 'empty');
    const emptyTabs = page.locator('.space-tabs-empty');
    await emptyTabs.waitFor({ state: 'visible' });
    assert.equal(await emptyTabs.getByRole('button').count(), 3);
    await page.screenshot({ path: '/tmp/space-tabs-empty-dark.png' });
    await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    await page.screenshot({ path: '/tmp/space-tabs-empty-light.png' });
    await page.reload();
    await emptyTabs.waitFor({ state: 'visible' });
    await page.locator('.app-boot-loader').waitFor({ state: 'hidden' });
    assert.equal(await emptyTabs.getByRole('button').count(), 3);
    await emptyTabs.getByRole('button', { name: 'Open 🦄 external', exact: true }).click();
    await page.getByRole('tab', { name: '🦄 external', exact: true }).waitFor();
    await emptyTabs.waitFor({ state: 'hidden' });
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('Release task'));
    assert.deepEqual(errors, []);
  } catch (error) { await fs.writeFile('/tmp/space-tabs-browser-server.log', log); throw error; }
  finally { await browser?.close(); server.kill('SIGTERM'); await new Promise(r => { if (server.exitCode !== null) r(); else server.on('exit', r); }); await fs.rm(tmp, { recursive: true, force: true }); }
});
