const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const net = require('node:net');
const { spawn } = require('node:child_process');
const { chromium } = require('@playwright/test');
const delay = ms => new Promise(r => setTimeout(r, ms));
test('cross-tab task references, original edits and drag transfers', { timeout: 120000 }, async () => {
  const root = path.resolve(__dirname, '../..');
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'space-tabs-test-'));
  const sock = net.createServer(); await new Promise(r => sock.listen(0, '127.0.0.1', r)); const port = sock.address().port; await new Promise(r => sock.close(r));
  let server = spawn(path.join(root, 'backend/.venv/bin/python'), [path.join(root, 'backend/tests/tabs_fixture_server.py'), tmp, String(port)], { cwd: root });
  let log = ''; server.stdout.on('data', b => log += b); server.stderr.on('data', b => log += b);
  let browser;
  try {
    const base = `http://127.0.0.1:${port}`;
    for (let i = 0; i < 80; i++) { try { if ((await fetch(base)).ok) break; } catch {} await delay(100); }
    browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const login = await context.request.post(base + '/api/login', { data: { username: 'admin', password: 'admin' } }); assert.equal(login.status(), 200);
    const spaces = await (await context.request.get(base + '/api/spaces')).json(); assert.ok(spaces.spaces.some(s => s.id === 'demo'));
    const listing = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(listing.tabs.length, 2);
    const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    // Restore through the existing space reference to exercise compatibility.
    await page.evaluate(() => { localStorage.setItem('taskScriptLastSpace', 'demo'); });
    await page.getByRole('button', { name: 'Switch space' }).click();
    const row = page.locator('.space-item').filter({ has: page.locator('.space-label', { hasText: /^demo$/ }) });
    await row.getByRole('button', { name: 'Connect', exact: true }).click();
    await page.locator('.space-tabs').waitFor({ state: 'visible' });
    await page.getByRole('tab', { name: 'main', exact: true }).waitFor();

    const main = listing.tabs.find(t => t.name === 'main');
    await page.getByRole('button', { name: 'Add', exact: true }).click();
    await page.getByRole('textbox', { name: 'Tab name', exact: true }).fill('refs');
    await page.getByRole('button', { name: 'Create', exact: true }).click();
    await page.getByRole('tab', { name: 'refs', exact: true }).waitFor();
    const tabs = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const refs = tabs.tabs.find(t => t.name === 'refs');
    const contents = async () => (await (await context.request.get(base + `/api/tab-spaces/${listing.id}/contents`)).json()).documents;
    const write = async (id, text) => {
      const documents = await contents(); const old = documents.find(d => d.id === id);
      const response = await context.request.post(base + `/api/tab-spaces/${listing.id}/documents`, { data: { changes: [{ id, expected: old.text, text }] } });
      assert.equal(response.status(), 200);
    };
    await write(main.id, '% Source\n#urgent @anna !todo\n1.10.2026-3.10.2026\n[ ] Check\n    % Child\n    4.10.2026\n');
    await write(refs.id, 'References:\n%%% main::Source\n');
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 1);
    assert.equal(await page.locator('.kanban-card').count(), 1);
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 1);
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await write(refs.id, 'References:\n%% main::Source\n');
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    assert.equal(await page.locator('.kanban-card').count(), 2);
    const sourceNode = page.locator('.task-node').filter({ hasText: 'Source' }).first();
    const originalBeforeDelete = (await contents()).find(d => d.id === main.id).text;
    await sourceNode.dblclick();
    await page.locator('#task-edit-delete').click();
    await page.locator('#task-delete-modal').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#task-delete-confirm-all').isVisible(), false);
    assert.match(await page.locator('#task-delete-message').textContent(), /original task and its subtasks will remain/);
    await page.locator('#task-delete-confirm').click();
    await page.waitForFunction(() => !document.querySelector('#task-editor').value.includes('%% main::Source'));
    assert.equal((await contents()).find(d => d.id === main.id).text, originalBeforeDelete);
    await page.locator('#undo-button').click();
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    await sourceNode.locator('input[type=checkbox]').check();
    await page.waitForTimeout(200);
    assert.match((await contents()).find(d => d.id === main.id).text, /\[x\] Check/);
    assert.equal((await contents()).find(d => d.id === refs.id).text, 'References:\n%% main::Source\n');
    await sourceNode.dblclick();
    await page.locator('#task-edit-title-input').fill('Renamed');
    await page.locator('#task-edit-save').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%% main::Renamed'));
    assert.match((await contents()).find(d => d.id === main.id).text, /% Renamed/);
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 2);
    const bar = page.locator('.timeline-bar').filter({ hasText: 'Renamed' });
    await bar.scrollIntoViewIfNeeded();
    const bounds = await bar.boundingBox();
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 40, bounds.y + bounds.height / 2, { steps: 5 }); await page.mouse.up();
    await page.waitForTimeout(250);
    assert.doesNotMatch((await contents()).find(d => d.id === main.id).text, /1\.10\.2026-3\.10\.2026/);
    assert.equal((await contents()).find(d => d.id === refs.id).text, 'References:\n%% main::Renamed\n');
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.locator('#undo-button').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('1.10.2026-3.10.2026'));
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await write(refs.id, '% Local\n');
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    const dragAcross = async (target, selector = '.graph-canvas') => {
      const source = page.locator('.task-node').filter({ hasText: 'Renamed' }).first();
      await source.waitFor({state: 'visible'});
      const from = await source.boundingBox(), tab = await page.getByRole('tab', { name: target, exact: true }).boundingBox();
      await page.mouse.move(from.x + from.width / 2, from.y + 18); await page.mouse.down();
      await page.mouse.move(tab.x + tab.width / 2, tab.y + tab.height / 2, { steps: 10 });
      await page.mouse.move(tab.x + tab.width / 2 + 1, tab.y + tab.height / 2);
      await page.waitForTimeout(1300);
      await page.screenshot({path: '/tmp/reference-drag-hover.png'});
      await page.waitForFunction(name => [...document.querySelectorAll('[role=tab]')].some(t => t.textContent.trim() === name && t.getAttribute('aria-selected') === 'true'), target, {timeout: 5000});
      const panel = await page.locator(selector).boundingBox();
      await page.mouse.move(panel.x + panel.width / 2, panel.y + (selector.includes('kanban') ? 20 : panel.height / 2), { steps: 5 }); await page.mouse.up();
      await page.getByRole('menu', { name: 'Place task in this tab' }).waitFor();
    };
    await dragAcross('refs');
    await page.getByRole('menuitem', { name: 'Reference this task only', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%%% main::Renamed'));
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    assert.equal(await page.locator('.kanban-card').count(), 2);
    await write(refs.id, '% Local\n');
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await dragAcross('refs');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%% main::Renamed'));
    assert.match((await contents()).find(d => d.id === main.id).text, /% Renamed/);
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await dragAcross('refs');
    await page.getByRole('menuitem', { name: 'Move task here', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('% Renamed'));
    assert.doesNotMatch((await contents()).find(d => d.id === main.id).text, /% Renamed/);
    assert.match((await contents()).find(d => d.id === refs.id).text, /%% refs::Renamed/);
    await page.reload();
    await page.getByRole('tab', { name: 'refs', exact: true }).waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length >= 3);
    await page.screenshot({ path: '/tmp/task-references.png' });

    assert.equal(await page.locator('.defs-diagnostics:not([hidden])').count(), 0);
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await dragAcross('main', '.timeline-viewport');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 2);
    assert.match((await contents()).find(d => d.id === main.id).text, /%% refs::Renamed/);
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    const beforeCancel = (await contents()).find(d => d.id === main.id).text;
    await dragAcross('main', '#code-editor .cm-content');
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('menu', { name: 'Place task in this tab' }).count(), 0);
    assert.equal((await contents()).find(d => d.id === main.id).text, beforeCancel);
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await dragAcross('main', '#code-editor .cm-content');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => (document.querySelector('#task-editor').value.match(/%% refs::Renamed/g) || []).length === 2);
    const current = (await contents()).find(d => d.id === refs.id).text;
    await write(refs.id, current.replace('!todo', ''));
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await dragAcross('main', '.kanban-column[data-state-tag="!todo"]');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => (document.querySelector('#task-editor').value.match(/%% refs::Renamed/g) || []).length === 3);
    assert.match((await contents()).find(d => d.id === refs.id).text, /!todo/);
    await page.locator('#code-editor .cm-content').click();
    await page.keyboard.press('Control+End');
    await page.keyboard.insertText('\n%% ');
    await page.keyboard.press('Control+Space');
    await page.locator('.cm-tooltip-autocomplete').getByText('refs::Renamed', {exact: true}).click();
    await page.waitForFunction(() => (document.querySelector('#task-editor').value.match(/%% refs::Renamed/g) || []).length === 4);
    await page.getByRole('button', { name: 'Close refs', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('[role=tab]')].some(tab => tab.textContent.trim() === 'refs'));
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 8);
    const closedListing = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const rename = await context.request.post(base + `/api/tab-spaces/${listing.id}/tabs/rename`, {data: {id: refs.id, name: 'library', revision: closedListing.revision}});
    assert.equal(rename.status(), 200);
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%% library::Renamed'));
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 8);
    await page.reload();
    await page.getByRole('tab', {name: 'main', exact: true}).waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 8);
    assert.equal(await page.locator('.defs-diagnostics:not([hidden])').count(), 0);
    assert.deepEqual(errors, []);
  } catch (error) { await fs.writeFile('/tmp/task-references-browser-server.log', log); throw error; }
  finally { await browser?.close(); server.kill('SIGTERM'); await new Promise(r => { if (server.exitCode !== null) r(); else server.on('exit', r); }); await fs.rm(tmp, { recursive: true, force: true }); }
});
