const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const net = require('node:net');
const { spawn } = require('node:child_process');
const { chromium } = require('@playwright/test');
const delay = ms => new Promise(r => setTimeout(r, ms));
test('cross-tab task references, original edits and drag transfers', { timeout: 120000 }, async () => {
  const root = path.resolve(__dirname, '../..');
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'space-tabs-test-'));
  const sock = net.createServer(); await new Promise(r => sock.listen(0, '127.0.0.1', r)); const port = sock.address().port; await new Promise(r => sock.close(r));
  let server = spawn(path.join(root, 'backend/.venv/bin/python'), [path.join(root, 'backend/tests/tabs_fixture_server.py'), tmp, String(port)], { cwd: root });
  let log = ''; server.stdout.on('data', b => log += b); server.stderr.on('data', b => log += b);
  let browser;
  try {
    const base = `http://127.0.0.1:${port}`;
    for (let i = 0; i < 80; i++) { try { if ((await fetch(base)).ok) break; } catch {} await delay(100); }
    browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const login = await context.request.post(base + '/api/login', { data: { username: 'admin', password: 'admin' } }); assert.equal(login.status(), 200);
    const spaces = await (await context.request.get(base + '/api/spaces')).json(); assert.ok(spaces.spaces.some(s => s.id === 'demo'));
    const listing = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    assert.equal(listing.tabs.length, 2);
    const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    // Restore through the existing space reference to exercise compatibility.
    await page.evaluate(() => { localStorage.setItem('taskScriptLastSpace', 'demo'); });
    await page.getByRole('button', { name: 'Switch space' }).click();
    const row = page.locator('.space-item').filter({ has: page.locator('.space-label', { hasText: /^demo$/ }) });
    await row.getByRole('button', { name: 'Connect', exact: true }).click();
    await page.locator('.space-tabs').waitFor({ state: 'visible' });
    await page.getByRole('tab', { name: 'main', exact: true }).waitFor();

    const main = listing.tabs.find(t => t.name === 'main');
    await page.getByRole('button', { name: 'Add', exact: true }).click();
    await page.getByRole('textbox', { name: 'Tab name', exact: true }).fill('refs');
    await page.getByRole('button', { name: 'Create', exact: true }).click();
    await page.getByRole('tab', { name: 'refs', exact: true }).waitFor();
    const tabs = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const refs = tabs.tabs.find(t => t.name === 'refs');
    const contents = async () => (await (await context.request.get(base + `/api/tab-spaces/${listing.id}/contents`)).json()).documents;
    const write = async (id, text) => {
      const documents = await contents(); const old = documents.find(d => d.id === id);
      const response = await context.request.post(base + `/api/tab-spaces/${listing.id}/documents`, { data: { changes: [{ id, expected: old.text, text }] } });
      assert.equal(response.status(), 200);
    };
    await write(main.id, '% Source\n#urgent @anna !todo\n1.10.2026-3.10.2026\n[ ] Check\n    % Child\n    4.10.2026\n');
    await write(refs.id, 'References:\n%%% main::Source\n');
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 1);
    assert.equal(await page.locator('.kanban-card').count(), 1);
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 1);
    await page.locator('.timeline-title').first().click({ modifiers: ['Control'] });
    await page.waitForFunction(() => [...document.querySelectorAll('[role=tab]')].some(tab => tab.textContent.trim() === 'main' && tab.getAttribute('aria-selected') === 'true'));
    await page.waitForFunction(() => [...document.querySelectorAll('.task-node.selected h4')].some(title => title.textContent === 'Source'));
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    for (const [type, value] of [['tag', '#urgent'], ['person', '@anna'], ['state', '!todo']]) {
      await page.locator(`.timeline-bar [data-type="${type}"][data-value="${value}"]`).first().dblclick();
      await page.locator('#slug-rename-modal').waitFor({ state: 'visible' });
      assert.equal(await page.locator('#slug-rename-current').inputValue(), value);
      assert.equal(await page.locator('#task-edit-modal').isVisible(), false);
      await page.locator('#slug-rename-close').click();
    }
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await write(refs.id, '% Local parent\n%%% main::Source\n');
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    const referenceNode = page.locator('.task-node').filter({ hasText: 'Source' }).first();
    const localParent = page.locator('.task-node').filter({ hasText: 'Local parent' }).first();
    const sourceBeforeReparent = (await contents()).find(d => d.id === main.id).text;
    await referenceNode.dragTo(localParent, { sourcePosition: { x: 30, y: 18 } });
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('    %%% main::Source'));
    assert.equal((await contents()).find(d => d.id === main.id).text, sourceBeforeReparent);
    await page.locator('#undo-button').click();
    await page.waitForFunction(() => !document.querySelector('#task-editor').value.includes('    %%% main::Source'));
    await write(refs.id, 'References:\n%% main::Source\n');
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    assert.equal(await page.locator('.kanban-card').count(), 2);
    const sourceNode = page.locator('.task-node').filter({ hasText: 'Source' }).first();
    const originalBeforeDelete = (await contents()).find(d => d.id === main.id).text;
    await sourceNode.dblclick();
    const editBodyBefore = await page.locator('#task-edit-code').inputValue();
    for (const [type, value] of [['tag', '#urgent'], ['person', '@anna'], ['state', '!todo']]) {
      await page.locator(`#task-edit-modal button.pill[data-type="${type}"][data-value="${value}"]`).dblclick();
      await page.locator('#slug-rename-modal').waitFor({ state: 'visible' });
      assert.equal(await page.locator('#slug-rename-current').inputValue(), value);
      await page.locator('#slug-rename-close').click();
      assert.equal(await page.locator('#task-edit-code').inputValue(), editBodyBefore);
    }
    const personOption = page.locator('#task-edit-modal button.pill[data-type="person"][data-value="@anna"]');
    await personOption.click();
    await page.waitForFunction(() => !document.querySelector('#task-edit-code').value.includes('@anna'));
    await personOption.click();
    await page.waitForFunction(() => document.querySelector('#task-edit-code').value.includes('@anna'));
    await page.locator('#task-edit-delete').click();
    await page.locator('#task-delete-modal').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#task-delete-confirm-all').isVisible(), false);
    assert.match(await page.locator('#task-delete-message').textContent(), /original task and its subtasks will remain/);
    await page.locator('#task-delete-confirm').click();
    await page.waitForFunction(() => !document.querySelector('#task-editor').value.includes('%% main::Source'));
    assert.equal((await contents()).find(d => d.id === main.id).text, originalBeforeDelete);
    await page.locator('#undo-button').click();
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    await sourceNode.locator('input[type=checkbox]').check();
    await page.waitForTimeout(200);
    assert.match((await contents()).find(d => d.id === main.id).text, /\[x\] Check/);
    assert.equal((await contents()).find(d => d.id === refs.id).text, 'References:\n%% main::Source\n');
    await sourceNode.dblclick();
    await page.locator('#task-edit-title-input').fill('Renamed');
    await page.locator('#task-edit-save').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%% main::Renamed'));
    assert.match((await contents()).find(d => d.id === main.id).text, /% Renamed/);
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 2);
    // Focus animation redraws timeline bars; wait for it to settle before dragging.
    await page.waitForTimeout(400);
    const bar = page.locator('.timeline-bar').filter({ hasText: 'Renamed' });
    await bar.scrollIntoViewIfNeeded();
    const bounds = await bar.boundingBox();
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 40, bounds.y + bounds.height / 2, { steps: 5 }); await page.mouse.up();
    await page.waitForTimeout(250);
    assert.doesNotMatch((await contents()).find(d => d.id === main.id).text, /1\.10\.2026-3\.10\.2026/);
    assert.equal((await contents()).find(d => d.id === refs.id).text, 'References:\n%% main::Renamed\n');
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.locator('#undo-button').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('1.10.2026-3.10.2026'));
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await write(refs.id, '% Local\n');
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    const dragAcross = async (target, selector = '.graph-canvas') => {
      const source = page.locator('.task-node').filter({ hasText: 'Renamed' }).first();
      await source.waitFor({state: 'visible'});
      const from = await source.boundingBox(), tab = await page.getByRole('tab', { name: target, exact: true }).boundingBox();
      await page.mouse.move(from.x + from.width / 2, from.y + 18); await page.mouse.down();
      await page.mouse.move(tab.x + tab.width / 2, tab.y + tab.height / 2, { steps: 10 });
      await page.mouse.move(tab.x + tab.width / 2 + 1, tab.y + tab.height / 2);
      await page.waitForTimeout(1300);
      await page.screenshot({path: '/tmp/reference-drag-hover.png'});
      await page.waitForFunction(name => [...document.querySelectorAll('[role=tab]')].some(t => t.textContent.trim() === name && t.getAttribute('aria-selected') === 'true'), target, {timeout: 5000});
      const panel = await page.locator(selector).boundingBox();
      await page.mouse.move(panel.x + panel.width / 2, panel.y + (selector.includes('kanban') ? 20 : panel.height / 2), { steps: 5 }); await page.mouse.up();
      await page.getByRole('menu', { name: 'Place task in this tab' }).waitFor();
    };
    await dragAcross('refs');
    await page.getByRole('menuitem', { name: 'Reference this task only', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%%% main::Renamed'));
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length === 2);
    assert.equal(await page.locator('.kanban-card').count(), 2);
    await write(refs.id, '% Local\n');
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await dragAcross('refs');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%% main::Renamed'));
    assert.match((await contents()).find(d => d.id === main.id).text, /% Renamed/);
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await dragAcross('refs');
    await page.getByRole('menuitem', { name: 'Move task here', exact: true }).click();
    await page.getByRole('button', { name: 'Just move task', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('% Renamed'));
    assert.doesNotMatch((await contents()).find(d => d.id === main.id).text, /% Renamed/);
    assert.match((await contents()).find(d => d.id === refs.id).text, /%% refs::Renamed/);
    await page.reload();
    await page.getByRole('tab', { name: 'refs', exact: true }).waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.task-node').length >= 3);
    await page.screenshot({ path: '/tmp/task-references.png' });

    assert.equal(await page.locator('.defs-diagnostics:not([hidden])').count(), 0);
    await page.getByRole('tab', { name: 'main', exact: true }).click();
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await dragAcross('main', '.timeline-viewport');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 2);
    assert.match((await contents()).find(d => d.id === main.id).text, /%% refs::Renamed/);
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    const beforeCancel = (await contents()).find(d => d.id === main.id).text;
    await dragAcross('main', '#code-editor .cm-content');
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('menu', { name: 'Place task in this tab' }).count(), 0);
    assert.equal((await contents()).find(d => d.id === main.id).text, beforeCancel);
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await dragAcross('main', '#code-editor .cm-content');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => (document.querySelector('#task-editor').value.match(/%% refs::Renamed/g) || []).length === 2);
    const current = (await contents()).find(d => d.id === refs.id).text;
    await write(refs.id, current.replace('!todo', ''));
    await page.getByRole('tab', { name: 'refs', exact: true }).click();
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await dragAcross('main', '.kanban-column[data-state-tag="!todo"]');
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.waitForFunction(() => (document.querySelector('#task-editor').value.match(/%% refs::Renamed/g) || []).length === 3);
    assert.match((await contents()).find(d => d.id === refs.id).text, /!todo/);
    await page.locator('#code-editor .cm-content').click();
    await page.keyboard.press('Control+End');
    await page.keyboard.insertText('\n%% ');
    await page.keyboard.press('Control+Space');
    await page.locator('.cm-tooltip-autocomplete').getByText('refs::Renamed', {exact: true}).click();
    await page.waitForFunction(() => (document.querySelector('#task-editor').value.match(/%% refs::Renamed/g) || []).length === 4);
    await page.getByRole('button', { name: 'Close refs', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('[role=tab]')].some(tab => tab.textContent.trim() === 'refs'));
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 8);
    const closedListing = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const rename = await context.request.post(base + `/api/tab-spaces/${listing.id}/tabs/rename`, {data: {id: refs.id, name: 'library', revision: closedListing.revision}});
    assert.equal(rename.status(), 200);
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%% library::Renamed'));
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 8);
    await page.locator('.timeline-bar').filter({ hasText: 'Renamed' }).first().locator('.timeline-title').click({ modifiers: ['Meta'] });
    await page.waitForFunction(() => [...document.querySelectorAll('[role=tab]')].some(tab => tab.textContent.trim() === 'library' && tab.getAttribute('aria-selected') === 'true'));
    await page.getByRole('button', { name: 'Close library', exact: true }).click();
    await page.waitForFunction(() => ![...document.querySelectorAll('.space-tab-select')].some(tab => tab.textContent.trim() === 'library') && [...document.querySelectorAll('.space-tab-select')].some(tab => tab.textContent.trim() === 'main' && tab.getAttribute('aria-selected') === 'true'));
    await page.reload();
    await page.getByRole('tab', {name: 'main', exact: true}).waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 8);
    assert.equal(await page.locator('.defs-diagnostics:not([hidden])').count(), 0);
    await write(main.id, '% Menu task\n1.10.2026-3.10.2026\n    % Menu child\n    2.10.2026\n');
    await page.waitForFunction(() => document.querySelectorAll('.timeline-bar').length === 2);
    const contextTask = selector => page.locator(selector).filter({ hasText: 'Menu task' }).first();
    await contextTask('.timeline-bar').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Reference this task only', exact: true }).click();
    await page.getByRole('menu', { name: 'Reference this task only', exact: true }).getByRole('menuitem', { name: 'library', exact: true }).click();
    await page.waitForTimeout(150);
    assert.match((await contents()).find(d => d.id === refs.id).text, /%%% main::Menu task/);
    await contextTask('.kanban-card').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Reference task and subtasks', exact: true }).click();
    await page.getByRole('menu', { name: 'Reference task and subtasks', exact: true }).getByRole('menuitem', { name: 'library', exact: true }).click();
    await page.waitForTimeout(150);
    assert.match((await contents()).find(d => d.id === refs.id).text, /\n%% main::Menu task/);
    await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await contextTask('.task-node').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Move to', exact: true }).click();
    await page.getByRole('menu', { name: 'Move to', exact: true }).getByRole('menuitem', { name: 'library', exact: true }).click();
    await page.getByRole('dialog', { name: 'Move to library', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click();
    assert.match((await contents()).find(d => d.id === main.id).text, /% Menu task/);
    await contextTask('.task-node').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Move to new tab', exact: true }).click();
    await page.getByRole('textbox', { name: 'Tab name', exact: true }).fill('moved');
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await page.getByRole('button', { name: 'Move to moved and leave reference', exact: true }).click();
    await page.waitForFunction(() => [...document.querySelectorAll('[role=tab]')].some(tab => tab.textContent.trim() === 'moved' && tab.getAttribute('aria-selected') === 'true'));
    assert.match((await contents()).find(d => d.id === main.id).text, /%% moved::Menu task/);
    assert.equal(await page.locator('.task-node').count(), 2);
    await contextTask('.task-node').click({ button: 'right' });
    assert.equal(await page.getByRole('menu', { name: 'Actions for Menu task', exact: true }).getByRole('separator').count(), 2);
    await page.getByRole('menuitem', { name: 'Archive', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.startsWith('%. Menu task'));
    await contextTask('.task-node').click({ button: 'right' });
    for (const name of ['Add task', 'Move task here', 'Reference tasks here', 'Reference tasks with subtasks here']) {
      assert.equal(await page.getByRole('menuitem', { name, exact: true }).isDisabled(), true);
    }
    await page.getByRole('menuitem', { name: 'Unarchive', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.startsWith('% Menu task'));
    await contextTask('.task-node').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Delete', exact: true }).click();
    await page.locator('#task-delete-confirm').click();
    await page.waitForFunction(() => !document.querySelector('#task-editor').value.includes('% Menu task'));
    assert.match(await page.locator('#task-editor').inputValue(), /% Menu child/);
    await write(refs.id, '% External\n1.10.2026\n    % External child\n    2.10.2026\n');
    const backgroundMenu = async selector => {
      const point = await page.locator(selector).evaluate(element => {
        const bounds = element.getBoundingClientRect();
        for (const y of [bounds.bottom - 100, bounds.top + bounds.height / 2, bounds.bottom - 24]) {
          for (const x of [bounds.right - 24, bounds.right - 100, bounds.left + bounds.width / 2]) {
            const target = document.elementFromPoint(x, y);
            if (target && element.contains(target) && !target.closest('.task-node, .timeline-bar, button')) return { x, y };
          }
        }
        throw new Error('No empty workspace point is visible');
      });
      await page.mouse.click(point.x, point.y, { button: 'right' });
      await page.getByRole('menu', { name: 'Workspace actions', exact: true }).waitFor();
    };
    await backgroundMenu('.graph-canvas');
    await page.getByRole('menuitem', { name: 'Reference tasks here', exact: true }).click();
    const picker = page.getByRole('dialog', { name: 'Reference tasks here', exact: true });
    await picker.getByLabel('Filter tabs', { exact: true }).selectOption({ label: 'library' });
    await picker.getByLabel('Search tasks', { exact: true }).fill('External');
    await picker.locator('.task-picker-item').filter({ has: page.locator('span', { hasText: /^External$/ }) }).getByRole('checkbox').check();
    await picker.getByRole('button', { name: 'Reference selected tasks', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('%%% library::External'));
    await page.locator('.task-node').filter({ hasText: 'External' }).first().click({ button: 'right' });
    const referenceMenu = page.locator('.task-context-menu');
    assert.equal(await referenceMenu.locator('.space-tab-menu-empty').textContent(), 'This is reference');
    assert.equal(await referenceMenu.locator('[role=menuitem]').count(), 6);
    assert.equal(await referenceMenu.locator('[role=menuitem]:disabled').count(), 0);
    assert.equal(await referenceMenu.locator('[role=menuitem]:enabled').count(), 6);
    await referenceMenu.getByRole('menuitem', { name: 'Delete', exact: true }).click();
    await page.locator('#task-delete-modal').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#task-delete-confirm-all').isVisible(), false);
    await page.locator('#task-delete-confirm').click();
    await page.waitForFunction(() => !document.querySelector('#task-editor').value.includes('%%% library::External'));
    assert.match((await contents()).find(d => d.id === refs.id).text, /% External/);
    const parentNode = page.locator('.task-node').filter({ hasText: 'Menu child' }).first();
    await parentNode.locator('h4').click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Add task', exact: true }).click();
    await page.locator('#task-edit-title-input').fill('Added child');
    await page.locator('#task-edit-save').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('    % Added child'));
    await page.locator('.kanban-card').filter({ hasText: 'Menu child' }).first().click({ button: 'right' });
    await page.getByRole('menuitem', { name: 'Reference tasks with subtasks here', exact: true }).click();
    const childrenPicker = page.getByRole('dialog', { name: 'Reference tasks with subtasks here', exact: true });
    await childrenPicker.getByLabel('Search tasks', { exact: true }).fill('External');
    await childrenPicker.locator('.task-picker-item').filter({ has: page.locator('span', { hasText: /^External$/ }) }).getByRole('checkbox').check();
    await childrenPicker.getByRole('button', { name: 'Reference selected tasks', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('    %% library::External'));
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    await backgroundMenu('.timeline-rows');
    await page.getByRole('menuitem', { name: 'Add task', exact: true }).click();
    await page.locator('#task-edit-title-input').fill('Timeline creation');
    await page.locator('#task-edit-save').click();
    await page.waitForFunction(() => [...document.querySelectorAll('.timeline-bar')].some(bar => bar.textContent.includes('Timeline creation')));
    await backgroundMenu('.timeline-rows');
    await page.getByRole('menuitem', { name: 'Move task here', exact: true }).click();
    const movePicker = page.getByRole('dialog', { name: 'Move tasks here', exact: true });
    await movePicker.getByLabel('Filter tabs', { exact: true }).selectOption({ label: 'library' });
    await movePicker.getByLabel('Search tasks', { exact: true }).fill('External child');
    await movePicker.getByRole('checkbox').check();
    await movePicker.getByRole('button', { name: 'Move selected tasks', exact: true }).click();
    await page.getByRole('button', { name: 'Just move task', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('% External child'));
    assert.doesNotMatch((await contents()).find(d => d.id === refs.id).text, /% External child/);
    const currentTabs = await (await context.request.get(base + '/api/tab-spaces?ref=demo')).json();
    const movedId = currentTabs.tabs.find(tab => tab.name === 'moved').id;
    const activeDocument = (await contents()).find(d => d.id === movedId);
    await write(activeDocument.id, activeDocument.text + '\n% [DEMO-42] Jira seed\n1.10.2026\n');
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('[DEMO-42]'));
    assert.equal((await context.request.get(base + `/api/jira-issue-suggestions?space=${listing.id}&query=DEMO-`)).status(), 200);
    assert.equal((await context.request.get(base + `/api/jira-issue-suggestions?space=${listing.id}&query=bad`)).status(), 400);
    assert.equal((await fetch(base + `/api/jira-issue-suggestions?space=${listing.id}&query=DEMO-`)).status, 401);
    await page.route('**/api/jira-issue-suggestions?**', route => route.fulfill({ json: { issues: [{ key: 'DEMO-42', name: 'Jira issue summary' }], configured: true } }));
    await backgroundMenu('.timeline-rows');
    await page.getByRole('menuitem', { name: 'Add task', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Link Jira', exact: true }).isVisible(), false);
    await page.route('**/api/jira-projects?**', route => route.fulfill({ json: { projects: [{ key: 'DEMO', name: 'DEMO' }] } }));
    const defs = currentTabs.tabs.find(tab => tab.kind === 'defs');
    const defsText = (await contents()).find(doc => doc.id === defs.id).text;
    await write(defs.id, defsText + '\njira:\n    base_url: https://jira.example.com\n    email: test@example.com\n    token: TEST\n');
    await page.getByRole('button', { name: 'Link Jira', exact: true }).waitFor();
    await page.locator('#task-edit-title-input').fill('Jira linked creation');
    await page.getByRole('button', { name: 'Link Jira', exact: true }).click();
    const jiraInput = page.getByRole('combobox', { name: 'Jira key', exact: true });
    await jiraInput.fill('de');
    assert.equal(await page.getByRole('listbox', { name: 'Jira suggestions', exact: true }).evaluate(el => getComputedStyle(el).position), 'absolute');
    await page.getByRole('option', { name: 'DEMO', exact: true }).click();
    assert.equal(await jiraInput.inputValue(), 'DEMO');
    await page.getByText('A new Jira task will be created in DEMO.', { exact: true }).waitFor();
    assert.equal(await page.getByRole('listbox', { name: 'Jira suggestions', exact: true }).isVisible(), false);
    await jiraInput.press('Enter');
    await page.getByText('A new Jira task will be created in DEMO.', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'Unlink Jira', exact: true }).evaluate(el => getComputedStyle(el).borderTopWidth), '0px');
    await page.getByRole('button', { name: 'Unlink Jira', exact: true }).click();
    assert.equal(await page.getByText('A new Jira task will be created in DEMO.', { exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Link Jira', exact: true }).click();
    await jiraInput.fill('DEMO-');
    await page.getByRole('option', { name: 'DEMO-42 Jira issue summary', exact: true }).click();
    await page.getByRole('button', { name: 'Unlink Jira', exact: true }).waitFor();
    assert.match(await page.locator('#task-edit-preview').textContent(), /DEMO-42/);
    await page.locator('#task-edit-save').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('% [DEMO-42] Jira linked creation'));
    await page.locator('.timeline-bar').filter({ hasText: 'Jira linked creation' }).first().locator('.timeline-title').dblclick();
    await page.getByRole('button', { name: 'Unlink Jira', exact: true }).click();
    await page.getByRole('button', { name: 'Link Jira', exact: true }).waitFor();
    await page.locator('#task-edit-save').click();
    await page.waitForFunction(() => document.querySelector('#task-editor').value.includes('% Jira linked creation'));
    assert.doesNotMatch(await page.locator('#task-editor').inputValue(), /\[DEMO-42\] Jira linked creation/);
    assert.deepEqual(errors, []);
  } catch (error) { await fs.writeFile('/tmp/task-references-browser-server.log', log); if (browser) { const page = browser.contexts()[0]?.pages()[0]; if (page) await fs.writeFile('/tmp/task-references-browser-dom.html', await page.content()); } throw error; }
  finally { await browser?.close(); server.kill('SIGTERM'); await new Promise(r => { if (server.exitCode !== null) r(); else server.on('exit', r); }); await fs.rm(tmp, { recursive: true, force: true }); }
});
